"""Aggregate balance worker output (JSON lines) into docs/balance-report.md.

usage: python tools/balance_report.py <dir with results_*.jsonl>
"""
import collections
import glob
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = sys.argv[1]
F = json.load(open(os.path.join(ROOT, "godot/data/factions.json"), encoding="utf-8"))
FACS = ["radiance", "sanctuary", "verdance", "abyss", "tempest"]
NAME = {f: F[f]["name"] for f in FACS}

rows = []
for p in glob.glob(os.path.join(src, "results_*.jsonl")):
    for line in open(p, encoding="utf-8"):
        line = line.strip()
        if line:
            rows.append(json.loads(line))
print("matches:", len(rows))

# faction score: wins as p0 + wins as p1, per difficulty and overall (mirror matches count for both seats)
def winner_fac(r):
    if not r["over"]:
        return None
    return r["p0"] if r["winner"] == 0 else r["p1"]

out = []
w = out.append
w("# Balance Report")
w("")
w("%d AI-versus-AI matches, every faction pairing (including mirrors), difficulties easy / normal / hard, two map seeds each. Player 0 is a normal-parameter AI in the human seat; player 1 is the opponent AI with the difficulty's income multiplier (the other difficulty parameters, attack timing and build delay, apply to both AIs). Matches are capped at 1200 game seconds. Generated by `tools/balance_report.py` from the Godot build." % len(rows))
w("")

# overall win rate per faction (both seats)
w("## Faction win rates (all difficulties, both seats)")
w("")
w("| Faction | Matches | Wins | Win rate | Avg match length (s) |")
w("|---|---|---|---|---|")
for f in FACS:
    played = [r for r in rows if r["p0"] == f or r["p1"] == f]
    wins = [r for r in played if winner_fac(r) == f]
    # mirror matches count once as played, once as won
    lens = [r["time"] for r in played if r["over"]]
    w("| %s | %d | %d | %d%% | %d |" % (NAME[f], len(played), len(wins), round(100.0 * len(wins) / max(1, len(played))), sum(lens) / max(1, len(lens))))
w("")

# head-to-head matrix from player-0 perspective (row beats column), all diffs
w("## Head-to-head (row = human seat, column = opponent; wins for the row faction out of matches played)")
w("")
w("| vs | " + " | ".join(NAME[f] for f in FACS) + " |")
w("|---|" + "---|" * len(FACS))
for a in FACS:
    cells = []
    for b in FACS:
        ms = [r for r in rows if r["p0"] == a and r["p1"] == b]
        ws = [r for r in ms if r["over"] and r["winner"] == 0]
        cells.append("%d/%d" % (len(ws), len(ms)))
    w("| **%s** | " % NAME[a] + " | ".join(cells) + " |")
w("")

# difficulty effect: human-seat win rate per difficulty
w("## Difficulty check (human-seat AI win rate against the opponent AI)")
w("")
w("| Difficulty | Matches | Human seat wins | Opponent wins | Unfinished | Avg length (s) |")
w("|---|---|---|---|---|---|")
for d in ["easy", "normal", "hard"]:
    ms = [r for r in rows if r["diff"] == d]
    h = sum(1 for r in ms if r["over"] and r["winner"] == 0)
    o = sum(1 for r in ms if r["over"] and r["winner"] == 1)
    u = sum(1 for r in ms if not r["over"])
    lens = [r["time"] for r in ms if r["over"]]
    w("| %s | %d | %d | %d | %d | %d |" % (d, len(ms), h, o, u, sum(lens) / max(1, len(lens))))
w("")

# match length distribution and first blood
lens = sorted(r["time"] for r in rows if r["over"])
if lens:
    w("Match length: shortest %d s, median %d s, longest %d s. First blood median %d s." % (lens[0], lens[len(lens) // 2], lens[-1], sorted(r["first_blood"] for r in rows if r["first_blood"] >= 0)[len([r for r in rows if r["first_blood"] >= 0]) // 2] if any(r["first_blood"] >= 0 for r in rows) else -1))
    w("")

# tier reached
w("## Tech progression")
w("")
w("| Faction | Matches | Reached Tier 2 | Reached Tier 3 | Avg peak supply |")
w("|---|---|---|---|---|")
for f in FACS:
    seats = [(r, 0) for r in rows if r["p0"] == f] + [(r, 1) for r in rows if r["p1"] == f]
    t2 = sum(1 for r, i in seats if r["tiers"][i] >= 2)
    t3 = sum(1 for r, i in seats if r["tiers"][i] >= 3)
    ps = [r["peak_supply"][i] for r, i in seats]
    w("| %s | %d | %d | %d | %.1f |" % (NAME[f], len(seats), t2, t3, sum(ps) / max(1, len(ps))))
w("")

# production: units never or rarely built
w("## Production (units, buildings and research the AI actually used)")
w("")
for f in FACS:
    seats = [(r, 0) for r in rows if r["p0"] == f] + [(r, 1) for r in rows if r["p1"] == f]
    n = len(seats)
    units = collections.Counter(); blds = collections.Counter(); res = collections.Counter()
    for r, i in seats:
        for k, v in r["produced"][i]["units"].items(): units[k] += v
        for k, v in r["produced"][i]["buildings"].items(): blds[k] += 1
        for k, v in r["produced"][i]["research"].items(): res[k] += 1
    w("### %s (%d seats)" % (NAME[f], n))
    w("")
    w("| Unit | Tier | Built per match | Building | Tier | Matches with it | Research | Matches with it |")
    w("|---|---|---|---|---|---|---|---|")
    ul = list(F[f]["units"].items()); bl = list(F[f]["buildings"].items()); rl = list(F[f].get("research", {}).items())
    for i in range(max(len(ul), len(bl), len(rl))):
        uc = "%s | %s | %.1f" % (ul[i][1]["name"], ul[i][1].get("tier", 1), units[ul[i][0]] / max(1, n)) if i < len(ul) else " | | "
        bc = "%s | %s | %d" % (bl[i][1]["name"], bl[i][1].get("tier", 1), blds[bl[i][0]]) if i < len(bl) else " | | "
        rc = "%s | %d" % (rl[i][1].get("name", rl[i][0]), res[rl[i][0]]) if i < len(rl) else " | "
        w("| %s | %s | %s |" % (uc, bc, rc))
    never_u = [ul_[1]["name"] for ul_ in ul if units[ul_[0]] == 0]
    never_b = [bl_[1]["name"] for bl_ in bl if blds[bl_[0]] == 0]
    never_r = [rl_[1].get("name", rl_[0]) for rl_ in rl if res[rl_[0]] == 0]
    w("")
    w("Never produced: units %s; buildings %s; research %s." % (", ".join(never_u) or "none", ", ".join(never_b) or "none", ", ".join(never_r) or "none"))
    w("")

# findings
w("## Findings")
w("")
findings = []
rates = {}
for f in FACS:
    played = [r for r in rows if r["p0"] == f or r["p1"] == f]
    wins = [r for r in played if winner_fac(r) == f]
    rates[f] = 100.0 * len(wins) / max(1, len(played))
best = max(rates, key=rates.get); worst = min(rates, key=rates.get)
findings.append("Strongest faction in AI hands: %s (%d%% win rate). Weakest: %s (%d%%). A spread wider than about 20 points means the rosters, not the AI, are unbalanced." % (NAME[best], rates[best], NAME[worst], rates[worst]))
unf = sum(1 for r in rows if not r["over"])
if unf:
    findings.append("%d matches hit the 1200 s cap without a winner; those pairings stall into a stand-off." % unf)
t3 = sum(1 for r in rows for i in (0, 1) if r["tiers"][i] >= 3)
findings.append("Tier 3 was reached in %d of %d seats. Ultimates and Tier 3 units barely feature in AI games, so Tier 3 balance is untested." % (t3, len(rows) * 2))
for line in findings:
    w("- " + line)
w("")
open(os.path.join(ROOT, "docs/balance-report.md"), "w", encoding="utf-8").write("\n".join(out) + "\n")
print("wrote docs/balance-report.md")
